export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_CURRENT_PASSWORD_REQUEST = 'GET_CURRENT_PASSWORD_REQUEST';
export const GET_CURRENT_PASSWORD_SUCCESS = 'GET_CURRENT_PASSWORD_SUCCESS';
